#!/bin/zsh -l

#SBATCH -p shared
#SBATCH -N 1
#SBATCH -t 01:30:00
#SBATCH -C haswell
#SBATCH --mem=8GB

module load python/2.7-anaconda
source activate optaux2

export LD_PRELOAD=/usr/lib64/libgfortran.so.3

srun python ../ME_community/simulate_model.py $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13
