#!/bin/zsh -l

#SBATCH -p shared
#SBATCH --image=docker:coltonlloyd/optaux:latest
#SBATCH --volume="/global/homes/c/cjlloyd:/output"
#SBATCH -t 01:30:00
#SBATCH -C haswell
#SBATCH --mem=8GB

shifterimg -v pull coltonlloyd/optaux:latest
shifter python3.6 ../ME_community/simulate_model.py $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14
