# Metabolites that can restore growth for each KO
ko_uptakes = {"['CS']": [u'EX_LalaDglu_e',
                         u'EX_LalaDgluMdap_e',
                         u'EX_LalaDgluMdapDala_e',
                         u'EX_LalaLglu_e',
                         u'EX_akg_e',
                         u'EX_arg__L_e',
                         u'EX_cit_e',
                         u'EX_fe3dcit_e',
                         u'EX_gln__L_e',
                         u'EX_glu__L_e',
                         u'EX_gthrd_e',
                         u'EX_orn_e',
                         u'EX_pro__L_e',
                         u'EX_progly_e'],
              "['DHORTS']": [u'EX_23ccmp_e',
                             u'EX_23cump_e',
                             u'EX_3cmp_e',
                             u'EX_3ump_e',
                             u'EX_cmp_e',
                             u'EX_csn_e',
                             u'EX_cytd_e',
                             u'EX_dcmp_e',
                             u'EX_dcyt_e',
                             u'EX_dump_e',
                             u'EX_duri_e',
                             u'EX_orot_e',
                             u'EX_uacgam_e',
                             u'EX_udpacgal_e',
                             u'EX_udpg_e',
                             u'EX_udpgal_e',
                             u'EX_udpglcur_e',
                             u'EX_ump_e',
                             u'EX_ura_e',
                             u'EX_uri_e'],
              "['GLUDy', 'GLUSy']": [u'EX_4abut_e',
                                     u'EX_LalaDglu_e',
                                     u'EX_LalaDgluMdap_e',
                                     u'EX_LalaDgluMdapDala_e',
                                     u'EX_LalaLglu_e',
                                     u'EX_agm_e',
                                     u'EX_ala__D_e',
                                     u'EX_ala__L_e',
                                     u'EX_alaala_e',
                                     u'EX_arg__L_e',
                                     u'EX_asn__L_e',
                                     u'EX_asp__L_e',
                                     u'EX_gln__L_e',
                                     u'EX_glu__L_e',
                                     u'EX_gthrd_e',
                                     u'EX_orn_e',
                                     u'EX_pro__L_e',
                                     u'EX_progly_e',
                                     u'EX_ptrc_e'],
              "['HISTD']": [u'EX_his__L_e']
              }
